### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by PercyDan54** [Adsicmes/osu_tools_rewrite#1]
```
Traceback (most recent call last):
  File "D:\Program Files\OSU Tools\osu_tools_rewrite-master\link_std!.py", line 1, in <module>
    from package.info import GosuInfoStd
  File "D:\Program Files\OSU Tools\osu_tools_rewrite-master\package\info.py", line 9, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
```

First_click_me!.py输出了：

`Requirement already satisfied: httpx==0.19.0 in c:\users\percydan\appdata\local\programs\python\python39-32\lib\site-packages (from -r requirements.txt (line 9)) (0.19.0)`

**Comment by Adsicmes** [comment]
超 真有人用💩山

你看看你是不是用了虚拟环境或者装了其他python
程序有很多要改进的地方
下次更新之后会整改

**Comment by PercyDan54** [comment]
> 超 真有人用💩山
> 
> 你看看你是不是用了虚拟环境或者装了其他python
> 程序有很多要改进的地方
> 下次更新之后会整改

整了一下发现是我python版本混了
不过还是无法启动：
```
Traceback (most recent call last):
  File "D:\Program Files\OSU Tools\osu_tools_rewrite-master\link_std!.py", line 30, in <module>
    from Memory64 import *
  File "C:\Users\PercyDan\AppData\Local\Programs\Python\Python39-32\lib\site-packages\Memory64\__init__.py", line 2, in <module>
    import ctypes, win32process, win32api, pygame
ModuleNotFoundError: No module named 'pygame'
```
安装pygame就好了（requirements漏了？）

**Comment by PercyDan54** [comment]
> 超 真有人用💩山
> 
> 你看看你是不是用了虚拟环境或者装了其他python
> 程序有很多要改进的地方
> 下次更新之后会整改

整了一下发现是我python版本混了
不过还是无法启动：
```
Traceback (most recent call last):
  File "D:\Program Files\OSU Tools\osu_tools_rewrite-master\link_std!.py", line 30, in <module>
    from Memory64 import *
  File "C:\Users\PercyDan\AppData\Local\Programs\Python\Python39-32\lib\site-packages\Memory64\__init__.py", line 2, in <module>
    import ctypes, win32process, win32api, pygame
ModuleNotFoundError: No module named 'pygame'
```
安装pygame就好了（requirements漏了？）

**Comment by Adsicmes** [comment]
我哪用过pygame草

**Comment by Adsicmes** [comment]
我的建议是
速速虚拟环境


下次更新之后打算整改
把配置文件都挑出来 换一下结构
打包成exe
